---
- name: ensure the install dir is available
  file:
    path: '{{ serviio_install_dir }}'
    state: directory
    owner: '{{ serviio_user }}'
    group: '{{ serviio_user }}'
    mode: 755
  sudo: yes
  tags: serviio

- name: download the bundle to the temporary location
  get_url:
    url: '{{ serviio_bundle_url }}'
    dest: '/tmp/{{ serviio_bundle_url | basename }}'
  tags: serviio

- name: unpack the bundle
  unarchive:
    src: '/tmp/{{ serviio_bundle_url | basename }}'
    dest: '{{ serviio_install_dir }}'
    copy: no
    creates: '{{ serviio_install_dir }}/serviio/bin/serviio.sh'
  tags: serviio
